# Generated by Django 4.2.1 on 2023-05-19 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(default=None, max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(default=None, max_length=20, verbose_name='last name')),
                ('date_of_birth', models.DateField(default=None, verbose_name='date of birth')),
                ('gender', models.CharField(db_column='gender', default=None, max_length=6, verbose_name='gender')),
                ('phone', models.CharField(db_column='phone_number', max_length=11, unique=True, verbose_name='phone number')),
                ('about', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default.png', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user1', models.CharField(max_length=255)),
                ('time', models.DateTimeField(db_column='Time')),
                ('user2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='title')),
                ('content', models.TextField(default=None, max_length=10000, verbose_name='content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('likes_number', models.IntegerField(db_column='likes_number', default=0, verbose_name='likes_number')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.OneToOneField(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receiver',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.OneToOneField(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sender',
            },
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('company_email', models.CharField(max_length=255)),
                ('likes_number', models.IntegerField(db_column='likes_number', default=0, verbose_name='likes_number')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('content', models.CharField(max_length=255)),
                ('time_field', models.DateTimeField(db_column='time_')),
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_fk', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='main.chat')),
                ('receiver_fk', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, to='main.receiver')),
                ('sender_fk', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='main.sender')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.OneToOneField(db_column='id_1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_2', models.ForeignKey(db_column='id_2', on_delete=django.db.models.deletion.CASCADE, related_name='id_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend',
                'unique_together': {('id_1', 'id_2')},
            },
        ),
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('sharing', models.IntegerField(db_column='Sharing')),
                ('time_of_sharing', models.DateTimeField(db_column='Time_Of_Sharing')),
                ('post', models.OneToOneField(db_column='Post_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.postmodel')),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
