# Generated by Django 4.2.1 on 2023-05-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_messages_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver_fk',
            field=models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_fk',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sender_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
